name: THREDDS_tutorial
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9.7  # Python version 3.9.7
    - cartopy       # Geographic plotting toolkit
#    - cython        # Transpile Python->C
    - dask          # Parallel processing library
    - datetime      # Library to work with dates
    - fnmatch       # Package to search lists
#    - ipython       # IPython interpreter and tools
#    - jupyter       # Jupyter federation architecture
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - numpy         # N-d array and numerics
#    - pandas        # Labeled array library
#    - proj4         # geographic projections
    - urllib        # Opens urls
    - xarray        # N-d labeled array library
    - xml.dom       # For opening xml files
